name: Publish release link to Jira

on:
  release:
    types: [created]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - uses: actions/checkout@v3
      - name: Install node-fetch
        run: npm i node-fetch@2
      - name: Test step
        env:
          RELEASE_BODY: ${{ github.event.release.body }}
          RELEASE_LINK: ${{ github.event.release.html_url }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKENS: ${{ secrets.JIRA_API_TOKENS }}
        run: node ./.github/workflows/test.js


